// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvZme7rh3zLzAVjUfb6KyTqbpNZuJog04',
    appId: '1:671279718092:web:8b1d6082c88bc6090c2c69',
    messagingSenderId: '671279718092',
    projectId: 'inventory-tracker-1182',
    authDomain: 'inventory-tracker-1182.firebaseapp.com',
    databaseURL: 'https://inventory-tracker-1182-default-rtdb.firebaseio.com',
    storageBucket: 'inventory-tracker-1182.firebasestorage.app',
    measurementId: 'G-78XWRY7PSR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2XWZMaKnNbGa5pRgCN32V7zAl5C-N6u4',
    appId: '1:671279718092:android:3a270bdcee9a6d770c2c69',
    messagingSenderId: '671279718092',
    projectId: 'inventory-tracker-1182',
    databaseURL: 'https://inventory-tracker-1182-default-rtdb.firebaseio.com',
    storageBucket: 'inventory-tracker-1182.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvliK5pHzew2SomvSbBMzOkVTK8SgUqY0',
    appId: '1:671279718092:ios:3abd0a5748c89ee50c2c69',
    messagingSenderId: '671279718092',
    projectId: 'inventory-tracker-1182',
    databaseURL: 'https://inventory-tracker-1182-default-rtdb.firebaseio.com',
    storageBucket: 'inventory-tracker-1182.firebasestorage.app',
    iosBundleId: 'com.example.inventoryTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvliK5pHzew2SomvSbBMzOkVTK8SgUqY0',
    appId: '1:671279718092:ios:3abd0a5748c89ee50c2c69',
    messagingSenderId: '671279718092',
    projectId: 'inventory-tracker-1182',
    databaseURL: 'https://inventory-tracker-1182-default-rtdb.firebaseio.com',
    storageBucket: 'inventory-tracker-1182.firebasestorage.app',
    iosBundleId: 'com.example.inventoryTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvZme7rh3zLzAVjUfb6KyTqbpNZuJog04',
    appId: '1:671279718092:web:5af8df23d716a6590c2c69',
    messagingSenderId: '671279718092',
    projectId: 'inventory-tracker-1182',
    authDomain: 'inventory-tracker-1182.firebaseapp.com',
    databaseURL: 'https://inventory-tracker-1182-default-rtdb.firebaseio.com',
    storageBucket: 'inventory-tracker-1182.firebasestorage.app',
    measurementId: 'G-X8PRWQNR28',
  );
}
